# Data file storing information about the game, mainly upgrade paths and description phrases
upgrades = {"buildspeed": {"startingValue": 1,
                           "names": ["Build Speed Upgrade 1", "Build Speed Upgrade 2", "Build Speed Upgrade 3"],
                           "descriptions": ["First upgrade to build speed.", "Second upgrade to build speed.", "Third upgrade to build speed."],
                           "costs": [{"science": 100, "credits": 250, "fuel": 0}, {"science": 120, "credits": 300, "fuel": 0}, {"science": 150, "credits": 500, "fuel": 0}],
                           "values": [1.1, 1.2, 1.25]},
            "buildcost": {"startingValue": 1,
                          "names": ["Build Cost Upgrade 1", "Build Cost Upgrade 2", "Build Cost Upgrade 3"],
                          "descriptions": ["First upgrade to build cost.", "Second upgrade to build cost.", "Third upgrade to build cost."],
                          "costs": [{"science": 5000, "credits": 5000, "fuel": 0}, {"science": 100, "credits": 500, "fuel": 0}, {"science": 150, "credits": 500, "fuel": 0}],
                          "values": [1.1, 1.2, 1.25]},
            "fuelcost": {"startingValue": 1,
                         "names": ["Fuel Cost Upgrade 1", "Fuel Cost Upgrade 2", "Fuel Cost Upgrade 3"],
                         "descriptions": ["First upgrade to fuel cost.", "Second upgrade to fuel cost.", "Third upgrade to fuel cost."],
                         "costs": [{"science": 300, "credits": 550, "fuel": 0}, {"science": 10, "credits": 100, "fuel": 0}, {"science": 150, "credits": 100, "fuel": 0}],
                         "values": [1.1, 1.2, 1.25]},
            "researchspeed": {"startingValue": 1,
                              "names": ["Research Speed Upgrade 1", "Research Speed Upgrade 2", "Research Speed Upgrade 3"],
                              "descriptions": ["First upgrade to research speed.", "Second upgrade to research speed.", "Third upgrade to research speed."],
                              "costs": [{"science": 300, "credits": 550, "fuel": 0}, {"science": 10, "credits": 100, "fuel": 0}, {"science": 150, "credits": 100, "fuel": 0}],
                              "values": [1.1, 1.2, 1.25]},
            "researchcost": {"startingValue": 1,
                             "names": ["Research Cost Upgrade 1", "Research Cost Upgrade 2", "Research Cost Upgrade 3"],
                             "descriptions": ["First upgrade to research cost.", "Second upgrade to research cost.", "Third upgrade to research cost."],
                             "costs": [{"science": 300, "credits": 550, "fuel": 0}, {"science": 10, "credits": 100, "fuel": 0}, {"science": 150, "credits": 100, "fuel": 0}],
                             "values": [1.1, 1.2, 1.25]},
            "shieldstrength": {"startingValue": 1,
                               "names": ["Shield Strenth Upgrade 1", "Shield Strength Upgrade 2", "Shield Strength Upgrade 3"],
                               "descriptions": ["First upgrade to shield strength.", "Second upgrade to shield strength.", "Third upgrade to shield strength."],
                               "costs": [{"science": 300, "credits": 550, "fuel": 0}, {"science": 10, "credits": 100, "fuel": 0}, {"science": 150, "credits": 100, "fuel": 0}],
                               "values": [1.1, 1.2, 1.25]},
            "shotdamage": {"startingValue": 1,
                           "names": ["Shot Damage Upgrade 1", "Shot Damage Upgrade 2", "Shot Damage Upgrade 3"],
                           "descriptions": ["First upgrade to shot damage.", "Second upgrade to shot damage.", "Third upgrade to shot damage."],
                           "costs": [{"science": 300, "credits": 550, "fuel": 0}, {"science": 10, "credits": 100, "fuel": 0}, {"science": 150, "credits": 100, "fuel": 0}],
                           "values": [1.1, 1.2, 1.25]}}