# Data file storing constants about all of the different ships in a giant nested dictonary
ShipData = {"testfighterblue": {"team": "blue",
                                "type": "fighter",
                                "size": 1,
                                "speed": 50,
                                "turn": 45,
                                "maxHealth": 100,
                                "numLasers": 1,
                                "numTurrets": 0,
                                "numTurboLasers": 0,
                                "maxTorpedos": 0,
                                "maxMissiles": 4},
            "testfighterred": {"team": "red",
                               "type": "fighter",
                               "size": 1,
                               "speed": 50,
                               "turn": 45,
                               "maxHealth": 100,
                               "numLasers": 1,
                               "numTurrets": 0,
                               "numTurboLasers": 0,
                               "maxTorpedos": 0,
                               "maxMissiles": 4},
            "testbattleshipblue": {"team": "blue",
                                   "type": "battleship",
                                   "size": 2,
                                   "speed": 2,
                                   "turn": 5,
                                   "maxHealth": 5000,
                                   "numLasers": 0,
                                   "numTurrets": 4,
                                   "numTurboLasers": 0,
                                   "maxTorpedos": 0,
                                   "maxMissiles": 4},
            "testbattleshipred": {"team": "red",
                                  "type": "battleship",
                                  "size": 2,
                                  "speed": 2,
                                  "turn": 5,
                                  "maxHealth": 5000,
                                  "numLasers": 0,
                                  "numTurrets": 4,
                                  "numTurboLasers": 0,
                                  "maxTorpedos": 0,
                                  "maxMissiles": 4}}
